# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yahtzee.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(660, 577)
        self.lblD1 = QtWidgets.QLabel(Dialog)
        self.lblD1.setGeometry(QtCore.QRect(30, 470, 61, 61))
        self.lblD1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblD1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblD1.setText("")
        self.lblD1.setObjectName("lblD1")
        self.lblD2 = QtWidgets.QLabel(Dialog)
        self.lblD2.setGeometry(QtCore.QRect(110, 470, 61, 61))
        self.lblD2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblD2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblD2.setText("")
        self.lblD2.setObjectName("lblD2")
        self.lblD3 = QtWidgets.QLabel(Dialog)
        self.lblD3.setGeometry(QtCore.QRect(190, 470, 61, 61))
        self.lblD3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblD3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblD3.setText("")
        self.lblD3.setObjectName("lblD3")
        self.lblD4 = QtWidgets.QLabel(Dialog)
        self.lblD4.setGeometry(QtCore.QRect(270, 470, 61, 61))
        self.lblD4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblD4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblD4.setText("")
        self.lblD4.setObjectName("lblD4")
        self.lblD5 = QtWidgets.QLabel(Dialog)
        self.lblD5.setGeometry(QtCore.QRect(350, 470, 61, 61))
        self.lblD5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblD5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblD5.setText("")
        self.lblD5.setObjectName("lblD5")
        self.chk1 = QtWidgets.QCheckBox(Dialog)
        self.chk1.setGeometry(QtCore.QRect(40, 540, 70, 17))
        self.chk1.setObjectName("chk1")
        self.chk2 = QtWidgets.QCheckBox(Dialog)
        self.chk2.setGeometry(QtCore.QRect(120, 540, 70, 17))
        self.chk2.setObjectName("chk2")
        self.chk3 = QtWidgets.QCheckBox(Dialog)
        self.chk3.setGeometry(QtCore.QRect(200, 540, 70, 17))
        self.chk3.setObjectName("chk3")
        self.chk4 = QtWidgets.QCheckBox(Dialog)
        self.chk4.setGeometry(QtCore.QRect(280, 540, 70, 17))
        self.chk4.setObjectName("chk4")
        self.chk5 = QtWidgets.QCheckBox(Dialog)
        self.chk5.setGeometry(QtCore.QRect(360, 540, 70, 17))
        self.chk5.setObjectName("chk5")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 261, 371))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.btnAces = QtWidgets.QPushButton(self.groupBox)
        self.btnAces.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.btnAces.setObjectName("btnAces")
        self.btnTwos = QtWidgets.QPushButton(self.groupBox)
        self.btnTwos.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.btnTwos.setObjectName("btnTwos")
        self.btnThrees = QtWidgets.QPushButton(self.groupBox)
        self.btnThrees.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.btnThrees.setObjectName("btnThrees")
        self.btnFours = QtWidgets.QPushButton(self.groupBox)
        self.btnFours.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.btnFours.setObjectName("btnFours")
        self.btnFives = QtWidgets.QPushButton(self.groupBox)
        self.btnFives.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.btnFives.setObjectName("btnFives")
        self.btnSixes = QtWidgets.QPushButton(self.groupBox)
        self.btnSixes.setGeometry(QtCore.QRect(20, 240, 75, 23))
        self.btnSixes.setObjectName("btnSixes")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 280, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 310, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 340, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setObjectName("label_3")
        self.txtAces = QtWidgets.QLineEdit(self.groupBox)
        self.txtAces.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.txtAces.setObjectName("txtAces")
        self.txtTwos = QtWidgets.QLineEdit(self.groupBox)
        self.txtTwos.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.txtTwos.setObjectName("txtTwos")
        self.txtThrees = QtWidgets.QLineEdit(self.groupBox)
        self.txtThrees.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.txtThrees.setObjectName("txtThrees")
        self.txtFours = QtWidgets.QLineEdit(self.groupBox)
        self.txtFours.setGeometry(QtCore.QRect(120, 160, 113, 20))
        self.txtFours.setObjectName("txtFours")
        self.txtFives = QtWidgets.QLineEdit(self.groupBox)
        self.txtFives.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.txtFives.setObjectName("txtFives")
        self.txtSixes = QtWidgets.QLineEdit(self.groupBox)
        self.txtSixes.setGeometry(QtCore.QRect(120, 240, 113, 20))
        self.txtSixes.setObjectName("txtSixes")
        self.txtTotalScore = QtWidgets.QLineEdit(self.groupBox)
        self.txtTotalScore.setGeometry(QtCore.QRect(120, 280, 113, 20))
        self.txtTotalScore.setObjectName("txtTotalScore")
        self.txtBonus = QtWidgets.QLineEdit(self.groupBox)
        self.txtBonus.setGeometry(QtCore.QRect(120, 310, 113, 20))
        self.txtBonus.setObjectName("txtBonus")
        self.txtUpperTotal = QtWidgets.QLineEdit(self.groupBox)
        self.txtUpperTotal.setGeometry(QtCore.QRect(120, 340, 113, 20))
        self.txtUpperTotal.setObjectName("txtUpperTotal")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 30, 271, 411))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_2.setPalette(palette)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn3OfAKind = QtWidgets.QPushButton(self.groupBox_2)
        self.btn3OfAKind.setGeometry(QtCore.QRect(30, 40, 75, 23))
        self.btn3OfAKind.setObjectName("btn3OfAKind")
        self.btn4OfAKind = QtWidgets.QPushButton(self.groupBox_2)
        self.btn4OfAKind.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.btn4OfAKind.setObjectName("btn4OfAKind")
        self.btnFullHouse = QtWidgets.QPushButton(self.groupBox_2)
        self.btnFullHouse.setGeometry(QtCore.QRect(30, 120, 75, 23))
        self.btnFullHouse.setObjectName("btnFullHouse")
        self.btnSmStraight = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSmStraight.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.btnSmStraight.setObjectName("btnSmStraight")
        self.btnLgStraight = QtWidgets.QPushButton(self.groupBox_2)
        self.btnLgStraight.setGeometry(QtCore.QRect(30, 200, 75, 23))
        self.btnLgStraight.setObjectName("btnLgStraight")
        self.btnYahtzee = QtWidgets.QPushButton(self.groupBox_2)
        self.btnYahtzee.setGeometry(QtCore.QRect(30, 240, 75, 23))
        self.btnYahtzee.setObjectName("btnYahtzee")
        self.btnChance = QtWidgets.QPushButton(self.groupBox_2)
        self.btnChance.setGeometry(QtCore.QRect(30, 280, 75, 23))
        self.btnChance.setObjectName("btnChance")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 380, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        self.label_4.setObjectName("label_4")
        self.txt3OfAKind = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt3OfAKind.setGeometry(QtCore.QRect(130, 40, 113, 20))
        self.txt3OfAKind.setObjectName("txt3OfAKind")
        self.txt4OfAKind = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt4OfAKind.setGeometry(QtCore.QRect(130, 80, 113, 20))
        self.txt4OfAKind.setObjectName("txt4OfAKind")
        self.txtFullHouse = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtFullHouse.setGeometry(QtCore.QRect(130, 120, 113, 20))
        self.txtFullHouse.setObjectName("txtFullHouse")
        self.txtSmStraight = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtSmStraight.setGeometry(QtCore.QRect(130, 160, 113, 20))
        self.txtSmStraight.setObjectName("txtSmStraight")
        self.txtLgStraight = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtLgStraight.setGeometry(QtCore.QRect(130, 200, 113, 20))
        self.txtLgStraight.setObjectName("txtLgStraight")
        self.txtYahtzee = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtYahtzee.setGeometry(QtCore.QRect(130, 240, 113, 20))
        self.txtYahtzee.setObjectName("txtYahtzee")
        self.txtChance = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtChance.setGeometry(QtCore.QRect(130, 280, 113, 20))
        self.txtChance.setObjectName("txtChance")
        self.txtYahtzeeBonus = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtYahtzeeBonus.setGeometry(QtCore.QRect(130, 320, 113, 20))
        self.txtYahtzeeBonus.setObjectName("txtYahtzeeBonus")
        self.txtLowerTotal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtLowerTotal.setGeometry(QtCore.QRect(130, 350, 113, 20))
        self.txtLowerTotal.setObjectName("txtLowerTotal")
        self.txtGrandTotal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtGrandTotal.setGeometry(QtCore.QRect(130, 380, 113, 20))
        self.txtGrandTotal.setObjectName("txtGrandTotal")
        self.btnRoll = QtWidgets.QPushButton(Dialog)
        self.btnRoll.setGeometry(QtCore.QRect(440, 480, 75, 41))
        self.btnRoll.setObjectName("btnRoll")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Yahtzee"))
        self.chk1.setText(_translate("Dialog", "Keep"))
        self.chk2.setText(_translate("Dialog", "Keep"))
        self.chk3.setText(_translate("Dialog", "Keep"))
        self.chk4.setText(_translate("Dialog", "Keep"))
        self.chk5.setText(_translate("Dialog", "Keep"))
        self.groupBox.setTitle(_translate("Dialog", "Upper Section"))
        self.btnAces.setText(_translate("Dialog", "Aces"))
        self.btnTwos.setText(_translate("Dialog", "Twos"))
        self.btnThrees.setText(_translate("Dialog", "Threes"))
        self.btnFours.setText(_translate("Dialog", "Fours"))
        self.btnFives.setText(_translate("Dialog", "Fives"))
        self.btnSixes.setText(_translate("Dialog", "Sixes"))
        self.label.setText(_translate("Dialog", "Total Score:"))
        self.label_2.setText(_translate("Dialog", "Bonus:"))
        self.label_3.setText(_translate("Dialog", "Total:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Lower Section"))
        self.btn3OfAKind.setText(_translate("Dialog", "3 of a kind"))
        self.btn4OfAKind.setText(_translate("Dialog", "4 of a kind"))
        self.btnFullHouse.setText(_translate("Dialog", "Full House"))
        self.btnSmStraight.setText(_translate("Dialog", "Sm. Straight"))
        self.btnLgStraight.setText(_translate("Dialog", "Lg. Straight"))
        self.btnYahtzee.setText(_translate("Dialog", "YAHTZEE"))
        self.btnChance.setText(_translate("Dialog", "Chance"))
        self.label_6.setText(_translate("Dialog", "Total:"))
        self.label_5.setText(_translate("Dialog", "YAHTZEE Bonus:"))
        self.label_4.setText(_translate("Dialog", "Grand Total:"))
        self.btnRoll.setText(_translate("Dialog", "Roll"))

